### PR TITLE
Czech Language Support

### PR DESCRIPTION
**Pull request by 14113**

### CODE REVIEW

**Comment by miks** [comment]
1) Please, replace tabs in fixture yaml files with spaces, otherwise tests are failing (https://travis-ci.org/kslazarev/numbers_and_words/builds/111765774)
2) it's better to have branch with meaning name not master

**Comment by dblock** [comment]
Bump @14113, want to finish this PR?

**Comment by 14113** [comment]
Sure, just no time right now.

**Comment by miks** [comment]
I corrected fixture yaml file locally, but tests (and therefore Czech language functionality) is pretty broken now. There is some work to do.

**Comment by jlduran** [comment]
Closed by #148. Thank you!

**Pull request closed without merging**
