### PR TITLE
Address RuboCop suggestions

### PR DESCRIPTION
**Pull request by jlduran**
- Add rubocop-rake plugin
- Style/NegatedIfElseCondition

### CODE REVIEW

**Comment by jlduran** [comment]
jruby is failing. I'll investigate.

**Comment by jlduran** [comment]
Travis CI is passing. Seems jruby-GitHub-related.
Retry within a few days.

**Comment by dblock** [comment]
Thank you! We do need to fix CI, even if unrelated, please? I'm happy to ignore jruby failures in the matrix of things.

**Comment by jlduran** [comment]
@dblock I'll wait until next year to retry the test. Hopefully it'll work by then. Thank you!

**Pull request merged**
